### ISSUE TITLE
does not compile with PHP 7.3.2 on Win64 PHPsdk 2.2-dev, complains about Syntax errors-update syntax errors disappear using libui-3.5-alpha compiled with VS2017, Still does not compile

### ISSUE THREAD

**Issue by EGYPHARAOH** [krakjoe/ui#56]
here the compiling output:
$ nmake

Microsoft (R) Program Maintenance Utility Version 14.16.27027.1
Copyright (C) Microsoft Corporation.  All rights reserved.

        type ext\pcre\php_pcre.def > D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\php7ts.dll.def
        "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\mc.exe" -h win32\ -r D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\ -x D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\ win32\build\wsyslog.mc
MC: Compiling win32\build\wsyslog.mc
ui.c
pecl\ui\classes/descriptor.h(27): error C2061: syntax error: identifier 'uiDrawTextFontDescriptor'
pecl\ui\classes/descriptor.h(29): error C2059: syntax error: '}'
pecl\ui\classes/font.h(24): error C2061: syntax error: identifier 'uiDrawTextFont'
pecl\ui\classes/font.h(25): error C2061: syntax error: identifier 'm'
pecl\ui\classes/font.h(25): error C2059: syntax error: ';'
pecl\ui\classes/font.h(28): error C2059: syntax error: '}'
pecl\ui\ui.c(385): error C2065: 'uiDrawFontFamilies': undeclared identifier
pecl\ui\ui.c(385): error C2065: 'families': undeclared identifier
pecl\ui\ui.c(385): warning C4552: '*': result of expression not used
pecl\ui\ui.c(394): error C2065: 'families': undeclared identifier
pecl\ui\ui.c(394): warning C4013: 'uiDrawListFontFamilies' undefined; assuming extern returning int
pecl\ui\ui.c(395): warning C4013: 'uiDrawFontFamiliesNumFamilies' undefined; assuming extern returning int
pecl\ui\ui.c(395): error C2065: 'families': undeclared identifier
pecl\ui\ui.c(396): warning C4013: 'uiDrawFontFamiliesFamily' undefined; assuming extern returning int
pecl\ui\ui.c(396): error C2065: 'families': undeclared identifier
pecl\ui\ui.c(396): warning C4047: 'function': 'const char *' differs in levels of indirection from 'int'
pecl\ui\ui.c(396): warning C4024: 'add_next_index_string': different types for formal and actual parameter 2
pecl\ui\ui.c(399): warning C4013: 'uiDrawFreeFontFamilies' undefined; assuming extern returning int
pecl\ui\ui.c(399): error C2065: 'families': undeclared identifier
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"' : return code '0x2'
Stop.

Looked at the 2 *.h files and did not located the mistake

**Comment by EGYPHARAOH** [comment]
OK there is an update
After looking at file dates I thought maybe the released working version for php7.1  used older than the current libui-4.x-alpha
I used libui3.5 after recompiling it under VS2017 x64 (thats totally another story)
the errors disappeared BUT the extention did not compile because of the following warnings:
ui.c
pecl\ui-release\ui.c(109): error C2039: 'initialized': is not a member of '_zend_fcall_info_cache'
Zend\zend_API.h(52): note: see declaration of '_zend_fcall_info_cache'
pecl\ui-release\ui.c(151): warning C4013: 'zm_startup_UI_EditableCombo' undefined; assuming extern returning int
pecl\ui-release\ui.c(155): warning C4013: 'zm_startup_UI_MenuItem' undefined; assuming extern returning int
pecl\ui-release\ui.c(163): warning C4013: 'zm_startup_UI_DrawMatrix' undefined; assuming extern returning int
pecl\ui-release\ui.c(169): warning C4013: 'php_ui_control_finalize' undefined; assuming extern returning int
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"' : return code '0x2'
Stop.
Now I am totally clueless what to do?
